# Importing Library

In [4]:
import tensorflow as tf
import numpy as np

## Making dataset

In [34]:
def windows_dataset(series, window_size, batch_size, shuffle_buffer):
    dataset = tf.data.Dataset.from_tensor_slices(series)
    dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
    dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))
    dataset = dataset.shuffle(shuffle_buffer).map(lambda window: (window[:-1], window[-1]))
    dataset = dataset.batch(batch_size).prefetch(1)
    return dataset

series = range(20)
dataset = windows_dataset(series, 5, 2, 10)

In [35]:
# for windows_dataset in dataset:
#     for val in windows_dataset:
#         print(val.numpy(), end=' ')
#     print()

# for window in dataset:
#     print(window.numpy())

for x, y in dataset:
    print(f'x = {x.numpy()}, y = {y.numpy()}')

x = [[ 0  1  2  3  4]
 [10 11 12 13 14]], y = [ 5 15]
x = [[ 8  9 10 11 12]
 [ 7  8  9 10 11]], y = [13 12]
x = [[12 13 14 15 16]
 [ 9 10 11 12 13]], y = [17 14]
x = [[14 15 16 17 18]
 [11 12 13 14 15]], y = [19 16]
x = [[ 2  3  4  5  6]
 [ 6  7  8  9 10]], y = [ 7 11]
x = [[3 4 5 6 7]
 [5 6 7 8 9]], y = [ 8 10]
x = [[13 14 15 16 17]
 [ 1  2  3  4  5]], y = [18  6]
x = [[4 5 6 7 8]], y = [9]
